"""Initial tables

Revision ID: dfdf155b73a6
Revises: 
Create Date: 2025-05-17 20:27:50.052406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfdf155b73a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('phone')

    with op.batch_alter_table('patient_details', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('male', 'female', 'other', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('blood_type',
               existing_type=mysql.ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('emergency_contact',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
        batch_op.alter_column('emergency_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('medical_insurance_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('allergies',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=1024),
               nullable=False)
        batch_op.alter_column('chronic_conditions',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=1024),
               nullable=False)
        batch_op.alter_column('medications',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=1024),
               nullable=False)
        batch_op.drop_constraint('patient_details_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['patient_id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('email')
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('patient_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('patient_details_ibfk_1', 'patients', ['patient_id'], ['patient_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('medications',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('chronic_conditions',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('allergies',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('medical_insurance_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.alter_column('emergency_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('emergency_contact',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('blood_type',
               existing_type=mysql.ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.ENUM('male', 'female', 'other', collation='utf8mb4_unicode_ci'),
               nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
